### ISSUE TITLE
Does gobble-babel support JSX?

### ISSUE THREAD

**Issue by joshbedo** [babel/gobble-babel#7]
I'm trying a basic example being compiled with gobble-babel and its complaining about a tag. I was wondering if the support on gobble-babel is the same as babel itself. Thanks!

![](https://api.monosnap.com/rpc/file/download?id=pjxnOrTOvqYWq3hOxTmqIxiJ6ukCG6)

**Comment by sebmck** [comment]
It does. Looks like you just have a syntax error in your code.

**Comment by joshbedo** [comment]
Yup, i figured it out.. only return one root dom node :)
