### ISSUE TITLE
hotlinking to resolve-rc

### ISSUE THREAD

**Issue by clintwood** [babel/gobble-babel#8]
As per babel 5.5.8 changelog the`resolve-rc` et al, the location has changed so the 'hotlink' to it is broken here.

@sebmck, @Rich-Harris, since hotlinking, as is done here is not ideally how to get babel to honor`.babelrc`how would you suggest going about doing this here.

BTW re-hotlinking to the new `resolve-rc` location works but I'd be happy to do a PR if you can suggest how this should be done without hotlinking to get `gobble-babel` to honor local`.babelrc`setting.

**Comment by sebmck** [comment]
Why was it hotlinking to `resolve-rc` in the first place? :/ Passing the absolute filename as the `filename` option is the expected way to go about it as it then performs the `.babelrc` lookup internally.

**Comment by Rich-Harris** [comment]
Thanks @clintwood - released as 5.5.8. It initially came from a PR, I accepted it because I didn't know setting `filename` would have that effect - the docs just say 'Filename for use in errors etc' ;-)

**Comment by clintwood** [comment]
Awesome, great, thanks!
